# 주제: 전국 배리어프리 문화예술관광지
(https://www.bigdata-culture.kr/bigdata/user/data_market/detail.do?id=573acce0-0337-11ee-a67e-69239d37dfae)
### 컬럼명 설명
- FCLTY_NM	시설명
- MRHST_NM	가맹점명
- CTGRY_ONE_NM	카테고리1명_레저/ 문화광관/ 전시 등
- CTGRY_TWO_NM	카테고리2명_공원/ 관광지/ 레저시설/ 영화/ 전시 등
- CTGRY_THREE_NM	카테고리3명_경마장/ 골프장/ 미술관 등
- CTPRVN_NM	시도명
- SIGNGU_NM	시군구명
- EMD_NM	읍면동명
- LI_NM	리명
- LNBR_NO	번지번호
- ROAD_NM	도로명
- BULD_NO	건물번호
- LC_LA	위치위도
- LC_LO	위치경도
- ZIP_NO	우편번호
- RDNMADR_NM	도로명주소명
- LNM_ADDR	지번주소
- TEL_NO	전화번호
- HMPG_URL	홈페이지URL
- BLOG_URL	블로그URL
- FACEBOOK_URL	페이스북URL
- INSTGRM_URL	인스타그램URL
- RSTDE_GUID_CN	휴무일안내내용
- OPER_TIME	운영시간
- FRE_PARKNG_AT	무료주차여부
- CHGD_PARKNG_AT	유료주차여부
- ENTRN_PRICE_AT	입장금액여부
- DSPSN_TOILET_ATMC_DOOR_AT	장애인화장실자동문여부
- WCHAIR_HOLD_AT	휠체어보유여부
- DSPSN_TOILET_AT	장애인화장실여부
- DSPSN_PRKPLCE_AT	장애인주차장여부
- LRGE_PARKNG_POSBL_AT	대주차가능여부
- GUID_DOG_ACP_POSBL_AT	안내견동반가능여부
- BRLL_GUID_AT	점자안내여부
- KLANG_VIC_GUID_AT	한국어음성안내여부
- LAST_UPDT_DE	최종수정일자

In [42]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [43]:
import matplotlib.pyplot as plt
import matplotlib
import matplotlib.font_manager as fm

# 폰트 설정
font_path = 'C:\\Windows\\Fonts\\gulim.ttc'
font = fm.FontProperties(fname=font_path).get_name()
matplotlib.rc('font', family=font)

In [44]:
df5=pd.read_csv('data/jeju_data.csv')
df5

,FCLTY_NM,MRHST_NM,CTGRY_ONE_NM,CTGRY_TWO_NM,CTGRY_THREE_NM,CTPRVN_NM,SIGNGU_NM,EMD_NM,LI_NM,LNBR_NO,...,ENTRN_PRICE_AT,DSPSN_TOILET_ATMC_DOOR_AT,WCHAIR_HOLD_AT,DSPSN_TOILET_AT,DSPSN_PRKPLCE_AT,LRGE_PARKNG_POSBL_AT,GUID_DOG_ACP_POSBL_AT,BRLL_GUID_AT,KLANG_VIC_GUID_AT,LAST_UPDT_DE
0,001스테이지,NaN,전시/공연,영화/연극/공연,N,서울특별시,종로구,동숭동,NaN,1-115 번지,...,Y,Y,N,Y,N,N,Y,Y,N,20221125
1,05스튜디오,NaN,전시/공연,전시/기념관,기타전시/박물관,경기도,파주시,탄현면,법흥리,1652-384 번지,...,N,N,N,N,N,N,N,N,N,20221125
2,072골프훈련소,NaN,레저/체육/공원,대형체육시설,N,경기도,안양시 동안구,평촌동,NaN,59-1 번지,...,Y,N,N,N,N,N,N,N,Y,20221125
3,1004섬수석미술관,NaN,전시/공연,전시/기념관,기타전시/박물관,전라남도,신안군,자은면,백산리,633-54 번지,...,N,N,N,N,N,N,N,N,N,20221125
4,123GC,NaN,레저/체육/공원,대형레저시설,퍼블릭골프장,경기도,고양시 덕양구,동산동,NaN,53-124 번지,...,Y,N,N,N,N,N,N,N,N,20221125
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12545,YG골프레인지,NaN,레저/체육/공원,대형체육시설,N,경기도,용인시 처인구,양지면,주북리,160-2 번지,...,Y,N,N,N,Y,Y,Y,N,Y,20221125
12546,YGKPOP클러스터(2023년3월예정),NaN,전시/공연,영화/연극/공연,공연/연극/문화센터,경기도,의정부시,산곡동,NaN,125-2 번지,...,N,N,N,N,N,N,N,N,N,20221125
12547,YJ호텔,NaN,레저/체육/공원,대형레저시설,요트장,경기도,가평군,설악면,회곡리,743-1 번지,...,Y,Y,N,N,N,N,Y,N,N,20221125
12548,YMCA고양국제청소년문화센터,NaN,전시/공연,영화/연극/공연,공연/연극/문화센터,경기도,고양시 일산동구,풍동,NaN,1399 번지,...,Y,Y,Y,N,Y,Y,Y,Y,Y,20221125
12549,YSL영아트홀,NaN,전시/공연,영화/연극/공연,공연/연극/문화센터,경기도,고양시 일산동구,마두동,NaN,908-3 번지,...,N,N,N,N,N,N,N,N,Y,20221125

In [45]:
df5=df5[df5['CTPRVN_NM']=='제주특별자치도']
df5 = df5[['FCLTY_NM', 'CTGRY_ONE_NM', 'CTGRY_TWO_NM', 'CTGRY_THREE_NM', 
         'SIGNGU_NM', 'FRE_PARKNG_AT', 'CHGD_PARKNG_AT', 'WCHAIR_HOLD_AT', 
         'DSPSN_TOILET_AT', 'DSPSN_PRKPLCE_AT', 'GUID_DOG_ACP_POSBL_AT', 
         'BRLL_GUID_AT', 'KLANG_VIC_GUID_AT']]
df5

,FCLTY_NM,CTGRY_ONE_NM,CTGRY_TWO_NM,CTGRY_THREE_NM,SIGNGU_NM,FRE_PARKNG_AT,CHGD_PARKNG_AT,WCHAIR_HOLD_AT,DSPSN_TOILET_AT,DSPSN_PRKPLCE_AT,GUID_DOG_ACP_POSBL_AT,BRLL_GUID_AT,KLANG_VIC_GUID_AT
58,9.81파크,문화관광/명소,관광지,테마공원/대형놀이공원,제주시,Y,N,N,Y,Y,N,N,N
85,가마해안도로,문화관광/명소,관광지,유명관광지,서귀포시,N,N,N,N,N,Y,N,N
102,가시리문화센터,전시/공연,영화/연극/공연,공연/연극/문화센터,서귀포시,Y,N,N,N,N,N,N,N
103,가시리창작지원센터,전시/공연,영화/연극/공연,공연/연극/문화센터,서귀포시,N,N,N,N,N,N,N,N
160,간드락게스트하우스,전시/공연,영화/연극/공연,공연/연극/문화센터,제주시,Y,N,N,N,N,N,N,N
...,...,...,...,...,...,...,...,...,...,...,...,...,...
12267,BEIN,전시/공연,영화/연극/공연,N,제주시,Y,N,N,Y,Y,N,N,N
12296,D.P.G골프아카데미,레저/체육/공원,대형체육시설,N,서귀포시,N,N,N,N,N,N,N,N
12345,ICC제주국제컨벤션센터,전시/공연,전시/기념관,컨벤션센터,서귀포시,Y,Y,Y,Y,Y,Y,Y,N
12436,M1971,레저/체육/공원,대형레저시설,요트장,서귀포시,Y,N,N,N,N,N,N,N
12518,TANK공연장,전시/공연,영화/연극/공연,N,제주시,N,N,N,N,N,N,N,N

In [46]:
display(df5.describe())
display(df5.info())

,FCLTY_NM,CTGRY_ONE_NM,CTGRY_TWO_NM,CTGRY_THREE_NM,SIGNGU_NM,FRE_PARKNG_AT,CHGD_PARKNG_AT,WCHAIR_HOLD_AT,DSPSN_TOILET_AT,DSPSN_PRKPLCE_AT,GUID_DOG_ACP_POSBL_AT,BRLL_GUID_AT,KLANG_VIC_GUID_AT
count,521,521,521,521,521,521,521,521,521,521,521,521,521
unique,519,3,7,37,2,2,2,2,2,2,2,2,2
top,섭지코지,전시/공연,관광지,기타전시/박물관,제주시,Y,N,N,N,N,N,N,N
freq,2,206,202,108,281,368,483,445,372,298,324,452,496

<class 'pandas.core.frame.DataFrame'>
Index: 521 entries, 58 to 12518
Data columns (total 13 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   FCLTY_NM               521 non-null    object
 1   CTGRY_ONE_NM           521 non-null    object
 2   CTGRY_TWO_NM           521 non-null    object
 3   CTGRY_THREE_NM         521 non-null    object
 4   SIGNGU_NM              521 non-null    object
 5   FRE_PARKNG_AT          521 non-null    object
 6   CHGD_PARKNG_AT         521 non-null    object
 7   WCHAIR_HOLD_AT         521 non-null    object
 8   DSPSN_TOILET_AT        521 non-null    object
 9   DSPSN_PRKPLCE_AT       521 non-null    object
 10  GUID_DOG_ACP_POSBL_AT  521 non-null    object
 11  BRLL_GUID_AT           521 non-null    object
 12  KLANG_VIC_GUID_AT      521 non-null    object
dtypes: object(13)
memory usage: 57.0+ KB

None

In [47]:
df5.isna().sum()

FCLTY_NM                 0
CTGRY_ONE_NM             0
CTGRY_TWO_NM             0
CTGRY_THREE_NM           0
SIGNGU_NM                0
FRE_PARKNG_AT            0
CHGD_PARKNG_AT           0
WCHAIR_HOLD_AT           0
DSPSN_TOILET_AT          0
DSPSN_PRKPLCE_AT         0
GUID_DOG_ACP_POSBL_AT    0
BRLL_GUID_AT             0
KLANG_VIC_GUID_AT        0
dtype: int64

In [48]:
df5.columns

Index(['FCLTY_NM', 'CTGRY_ONE_NM', 'CTGRY_TWO_NM', 'CTGRY_THREE_NM',
       'SIGNGU_NM', 'FRE_PARKNG_AT', 'CHGD_PARKNG_AT', 'WCHAIR_HOLD_AT',
       'DSPSN_TOILET_AT', 'DSPSN_PRKPLCE_AT', 'GUID_DOG_ACP_POSBL_AT',
       'BRLL_GUID_AT', 'KLANG_VIC_GUID_AT'],
      dtype='object')

In [49]:
df5['PARKNG_AT'] = 'Y'
df5.loc[(df5['FRE_PARKNG_AT'] == 'N') & (df5['CHGD_PARKNG_AT'] == 'N'), 'PARKNG_AT'] = 'N'
df5.drop(['FRE_PARKNG_AT', 'CHGD_PARKNG_AT'], axis=1, inplace=True)
df5

,FCLTY_NM,CTGRY_ONE_NM,CTGRY_TWO_NM,CTGRY_THREE_NM,SIGNGU_NM,WCHAIR_HOLD_AT,DSPSN_TOILET_AT,DSPSN_PRKPLCE_AT,GUID_DOG_ACP_POSBL_AT,BRLL_GUID_AT,KLANG_VIC_GUID_AT,PARKNG_AT
58,9.81파크,문화관광/명소,관광지,테마공원/대형놀이공원,제주시,N,Y,Y,N,N,N,Y
85,가마해안도로,문화관광/명소,관광지,유명관광지,서귀포시,N,N,N,Y,N,N,N
102,가시리문화센터,전시/공연,영화/연극/공연,공연/연극/문화센터,서귀포시,N,N,N,N,N,N,Y
103,가시리창작지원센터,전시/공연,영화/연극/공연,공연/연극/문화센터,서귀포시,N,N,N,N,N,N,N
160,간드락게스트하우스,전시/공연,영화/연극/공연,공연/연극/문화센터,제주시,N,N,N,N,N,N,Y
...,...,...,...,...,...,...,...,...,...,...,...,...
12267,BEIN,전시/공연,영화/연극/공연,N,제주시,N,Y,Y,N,N,N,Y
12296,D.P.G골프아카데미,레저/체육/공원,대형체육시설,N,서귀포시,N,N,N,N,N,N,N
12345,ICC제주국제컨벤션센터,전시/공연,전시/기념관,컨벤션센터,서귀포시,Y,Y,Y,Y,Y,N,Y
12436,M1971,레저/체육/공원,대형레저시설,요트장,서귀포시,N,N,N,N,N,N,Y
12518,TANK공연장,전시/공연,영화/연극/공연,N,제주시,N,N,N,N,N,N,N

In [50]:
from sklearn.preprocessing import LabelEncoder
label=LabelEncoder()

In [51]:
df5[['WCHAIR_HOLD_AT','DSPSN_TOILET_AT','DSPSN_PRKPLCE_AT','GUID_DOG_ACP_POSBL_AT','BRLL_GUID_AT','KLANG_VIC_GUID_AT','PARKNG_AT']]=df5[['WCHAIR_HOLD_AT','DSPSN_TOILET_AT','DSPSN_PRKPLCE_AT','GUID_DOG_ACP_POSBL_AT','BRLL_GUID_AT','KLANG_VIC_GUID_AT','PARKNG_AT']].apply(label.fit_transform)

In [52]:
df5
# 0: N, 1: Y

,FCLTY_NM,CTGRY_ONE_NM,CTGRY_TWO_NM,CTGRY_THREE_NM,SIGNGU_NM,WCHAIR_HOLD_AT,DSPSN_TOILET_AT,DSPSN_PRKPLCE_AT,GUID_DOG_ACP_POSBL_AT,BRLL_GUID_AT,KLANG_VIC_GUID_AT,PARKNG_AT
58,9.81파크,문화관광/명소,관광지,테마공원/대형놀이공원,제주시,0,1,1,0,0,0,1
85,가마해안도로,문화관광/명소,관광지,유명관광지,서귀포시,0,0,0,1,0,0,0
102,가시리문화센터,전시/공연,영화/연극/공연,공연/연극/문화센터,서귀포시,0,0,0,0,0,0,1
103,가시리창작지원센터,전시/공연,영화/연극/공연,공연/연극/문화센터,서귀포시,0,0,0,0,0,0,0
160,간드락게스트하우스,전시/공연,영화/연극/공연,공연/연극/문화센터,제주시,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...
12267,BEIN,전시/공연,영화/연극/공연,N,제주시,0,1,1,0,0,0,1
12296,D.P.G골프아카데미,레저/체육/공원,대형체육시설,N,서귀포시,0,0,0,0,0,0,0
12345,ICC제주국제컨벤션센터,전시/공연,전시/기념관,컨벤션센터,서귀포시,1,1,1,1,1,0,1
12436,M1971,레저/체육/공원,대형레저시설,요트장,서귀포시,0,0,0,0,0,0,1
12518,TANK공연장,전시/공연,영화/연극/공연,N,제주시,0,0,0,0,0,0,0

In [65]:
import pandas as pd

df2 = pd.read_csv('./data/tn_visit_area_info_방문지정보_H.csv')
df2
jeju_df = df2[df2['ROAD_NM_ADDR'].str.contains('제주', na=False)]
jeju_df.info()
jeju_df
df3 = pd.read_csv('./data/tn_traveller_master_여행객 Master_H.csv')
df3
jeju_df.columns
df3.columns
df4 = pd.read_csv('./data/tn_travel_여행_H.csv')
df4
df3_4 = pd.merge(df3, df4, on='TRAVELER_ID', how='inner')
df3_4
merged_df = pd.merge(jeju_df, df3_4, on='TRAVEL_ID', how='inner')
merged_df
merged_df.columns
df = merged_df.drop(['VISIT_AREA_ID', 'VISIT_ORDER',
                     'VISIT_START_YMD', 'VISIT_END_YMD', 'ROAD_NM_ADDR', 'LOTNO_ADDR',
                     'X_COORD', 'Y_COORD', 'ROAD_NM_CD', 'LOTNO_CD',
                     'RESIDENCE_TIME_MIN', 'VISIT_AREA_TYPE_CD', 'REVISIT_YN',
                     'VISIT_CHC_REASON_CD', 'LODGING_TYPE_CD',
                     'RCMDTN_INTENTION', 'SGG_CD', 'TRAVELER_ID', 'RESIDENCE_SGG_CD',
                     'EDU_NM', 'EDU_FNSH_SE', 'MARR_STTS',
                     'FAMILY_MEMB', 'JOB_NM', 'JOB_ETC', 'INCOME', 'HOUSE_INCOME',
                     'TRAVEL_TERM', 'TRAVEL_NUM', 'TRAVEL_LIKE_SIDO_1', 'TRAVEL_LIKE_SGG_1',
                     'TRAVEL_LIKE_SIDO_2', 'TRAVEL_LIKE_SGG_2', 'TRAVEL_LIKE_SIDO_3',
                     'TRAVEL_LIKE_SGG_3', 'TRAVEL_STYL_1', 'TRAVEL_STYL_2', 'TRAVEL_STYL_3',
                     'TRAVEL_STYL_4', 'TRAVEL_STYL_5', 'TRAVEL_STYL_6', 'TRAVEL_STYL_7',
                     'TRAVEL_STYL_8', 'TRAVEL_STATUS_RESIDENCE', 'TRAVEL_STATUS_DESTINATION',
                     'TRAVEL_STATUS_ACCOMPANY', 'TRAVEL_STATUS_YMD', 'TRAVEL_MOTIVE_1',
                     'TRAVEL_MOTIVE_2', 'TRAVEL_MOTIVE_3', 'TRAVEL_COMPANIONS_NUM',
                     'TRAVEL_NM', 'TRAVEL_PURPOSE', 'TRAVEL_START_YMD', 'TRAVEL_END_YMD',
                     'MVMN_NM', 'TRAVEL_MISSION', 'TRAVEL_MISSION_CHECK', 'POI_ID',
                     'POI_NM', 'TRAVEL_PERSONA', 'REVISIT_INTENTION'], axis=1)
df
df = df.dropna(axis=0)
df.isna().sum()
# df = df[~df['VISIT_AREA_NM'].str.contains('집')]
# df = df[~df['VISIT_AREA_NM'].str.contains('아파트')]
# df = df[~df['VISIT_AREA_NM'].str.contains('공항')]
# df = df[~df['VISIT_AREA_NM'].str.contains('렌터카')]
# df = df[~df['VISIT_AREA_NM'].str.contains('커피')]
# df = df[~df['VISIT_AREA_NM'].str.contains('카페')]
# df = df[~df['VISIT_AREA_NM'].str.contains('스타벅스')]
# df = df[~df['VISIT_AREA_NM'].str.contains('투썸플레이스')]
# df = df[~df['VISIT_AREA_NM'].str.contains('빽다방')]
# df = df[~df['VISIT_AREA_NM'].str.contains('호텔')]
# df = df[~df['VISIT_AREA_NM'].str.contains('리조트')]
# df = df[~df['VISIT_AREA_NM'].str.contains('펜션')]
# df = df[~df['VISIT_AREA_NM'].str.contains('하우스')]
# df = df[~df['VISIT_AREA_NM'].str.contains('식당')]
# df = df[~df['VISIT_AREA_NM'].str.contains('마트')]
# df = df[~df['VISIT_AREA_NM'].str.contains('GS25')]
# df = df[~df['VISIT_AREA_NM'].str.contains('CU')]
# df = df[~df['VISIT_AREA_NM'].str.contains('인생네컷')]
df
df['VISIT_AREA_NM'] = df['VISIT_AREA_NM'].str.replace(' ', '')
df = df.rename(columns={'VISIT_AREA_NM': 'FCLTY_NM'})
df

<class 'pandas.core.frame.DataFrame'>
Index: 23794 entries, 2413 to 46008
Data columns (total 23 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   VISIT_AREA_ID        23794 non-null  int64
 1   TRAVEL_ID            23794 non-null  object
 2   VISIT_ORDER          23794 non-null  int64
 3   VISIT_AREA_NM        23794 non-null  object
 4   VISIT_START_YMD      23794 non-null  object
 5   VISIT_END_YMD        23794 non-null  object
 6   ROAD_NM_ADDR         23794 non-null  object
 7   LOTNO_ADDR           23420 non-null  object
 8   X_COORD              22854 non-null  float64
 9   Y_COORD              22854 non-null  float64
 10  ROAD_NM_CD           175 non-null    float64
 11  LOTNO_CD             175 non-null    float64
 12  POI_ID               22896 non-null  object
 13  POI_NM               22896 non-null  object
 14  RESIDENCE_TIME_MIN   23675 non-null  float64
 15  VISIT_AREA_TYPE_CD   23794 non-null  int64
 16  REVISIT_YN           23455 non-null  object
 17  VISIT_CHC_REASON_CD  23455 non-null  float64
 18  LODGING_TYPE_CD      4463 non-null   float64
 19  DGSTFN               23453 non-null  float64
 20  REVISIT_INTENTION    23453 non-null  float64
 21  RCMDTN_INTENTION     23453 non-null  float64
 22  SGG_CD               394 non-null    float64
dtypes: float64(11), int64(3), object(9)
memory usage: 4.4+ MB

       TRAVEL_ID    FCLTY_NM  DGSTFN GENDER  AGE_GRP
1      e_e004090      제주국제공항     4.0      남       20
3      e_e004808      제주국제공항     4.0      여       20
4      e_e005480      제주국제공항     4.0      여       30
6      e_e005858      제주국제공항     5.0      여       20
8      g_g005682    제주원렌터카본점     4.0      남       20
...          ...         ...     ...    ...      ...
23786  h_h006872   항파두리항몽유적지     4.0      여       30
23787  h_h006872        소길별하     4.0      여       30
23790  h_h006874        꼬스뗀뇨     3.0      여       50
23791  h_h006874     마이피기팬트리     4.0      여       50
23792  h_h006874  민경이네어등포해녀촌     4.0      여       50

[23453 rows x 5 columns]

In [68]:
real_df=pd.merge(df5, df, on='FCLTY_NM',how='inner')
real_df

,FCLTY_NM,CTGRY_ONE_NM,CTGRY_TWO_NM,CTGRY_THREE_NM,SIGNGU_NM,WCHAIR_HOLD_AT,DSPSN_TOILET_AT,DSPSN_PRKPLCE_AT,GUID_DOG_ACP_POSBL_AT,BRLL_GUID_AT,KLANG_VIC_GUID_AT,PARKNG_AT,TRAVEL_ID,DGSTFN,GENDER,AGE_GRP
0,9.81파크,문화관광/명소,관광지,테마공원/대형놀이공원,제주시,0,1,1,0,0,0,1,h_h000009,5.0,남,40
1,9.81파크,문화관광/명소,관광지,테마공원/대형놀이공원,제주시,0,1,1,0,0,0,1,h_h000172,5.0,남,20
2,9.81파크,문화관광/명소,관광지,테마공원/대형놀이공원,제주시,0,1,1,0,0,0,1,h_h000203,5.0,남,20
3,9.81파크,문화관광/명소,관광지,테마공원/대형놀이공원,제주시,0,1,1,0,0,0,1,h_h000233,5.0,여,30
4,9.81파크,문화관광/명소,관광지,테마공원/대형놀이공원,제주시,0,1,1,0,0,0,1,h_h000263,5.0,여,40
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1997,ICC제주국제컨벤션센터,전시/공연,전시/기념관,컨벤션센터,서귀포시,1,1,1,1,1,0,1,h_h000078,4.0,여,40
1998,ICC제주국제컨벤션센터,전시/공연,전시/기념관,컨벤션센터,서귀포시,1,1,1,1,1,0,1,h_h000870,5.0,남,30
1999,ICC제주국제컨벤션센터,전시/공연,전시/기념관,컨벤션센터,서귀포시,1,1,1,1,1,0,1,h_h002119,4.0,남,30
2000,ICC제주국제컨벤션센터,전시/공연,전시/기념관,컨벤션센터,서귀포시,1,1,1,1,1,0,1,h_h002873,3.0,여,30
2001,ICC제주국제컨벤션센터,전시/공연,전시/기념관,컨벤션센터,서귀포시,1,1,1,1,1,0,1,h_h006612,4.0,남,50

In [69]:
real_df['FCLTY_NM'].nunique()

108

In [70]:
real_df.isna().sum()

FCLTY_NM                 0
CTGRY_ONE_NM             0
CTGRY_TWO_NM             0
CTGRY_THREE_NM           0
SIGNGU_NM                0
WCHAIR_HOLD_AT           0
DSPSN_TOILET_AT          0
DSPSN_PRKPLCE_AT         0
GUID_DOG_ACP_POSBL_AT    0
BRLL_GUID_AT             0
KLANG_VIC_GUID_AT        0
PARKNG_AT                0
TRAVEL_ID                0
DGSTFN                   0
GENDER                   0
AGE_GRP                  0
dtype: int64